# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d04152f74d25671687e028b06d4810a81774b4c277b4ade27ec79af6379c81c8906aa232fa5adaf3976dd407869f269bcd69b5bd3eaf759b277268891352db1

test:
  secret_key_base: f5e25aff6bf7a22561253e1412148747d173312ce2ac344fc767aa32f5da8fc42e0c718767f5b190be3ea6e938be8f3ae24b446072e26e20c0283ebef6c770b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
